baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Petras Site'
theme = 'hugo-theme-stack'

[[module.imports]]
path = 'github.com/CaiJimmy/hugo-theme-stack/v3'

[params.sidebar]
  compact = false
  subtitle = 'Welcome to my documentation'
  emoji = '💀'

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = 'img/avatar.png'

[[params.widgets.homepage]]
type = 'search'

[[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/Kayigis/Second_"

    [menu.social.params]
    icon = "brand-github"